language: node_js
node_js:
- '6'
script: npm run lint
after_success: npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: tV8vsUC9ecxZjac37v3WlCs0DzMXn+LzSqVRJYXeZTKxhl/rV31RWO4ssZgqlNs6zH+ocWgGDk2QUD5cQd+WnMJIQZj0jTV5f6sfnAK/pWitGy7s95HeIbRgRcF4Il06G/LxKxN1Ck0iY8qS5CQwifnccxDV4+Zo8uX1RCFIrZVe2FRhnot2Ns9dQbIbQZpcyCtWO6VgVp3ki9RrLeyAqbpSouJIZ3j5vzEu7IAGEuTNsnhwnhMksAO0cUz8dqkR0LevDR+QSCD+E6JvbZ2KhWCFdVmR+kE8lx6XmGU1YbZiD4O+IhVfF1IzeF40OeGPA4bi2T6pRqFgl1RvP2APEoELYfeOvgHjCXv06pw0xrvr1wGGyj7y9ESXtcYAIfqkBlaAJyEqysDAsViOebWoQA2H+8EleG1cg1c5BSHlIWE5fcr2OwnZSDpeGGXHWjWc1fKVRoqQbPbBYPCiUFqx98cYppDBtY6JnxSd/guOabWT4zFczK5SD5gglMkirABObroxV3ZWiCRQcit+10982VRLE2QLQ5RdHFTiW3zxRpDe83fdCSFGUsEEYghZ3lab5bIsv4a4GWJ7qTeqvP72Dvelu0eqbU7atOBIv+j3MJNIpffxF5bCqVnebIFREc1bilcx1WxywAz/YmieqN5gZkYcA981BhFkwHQlFSF25u4=
cache: yarn
