language: node_js
node_js:
- '6'
script: npm run lint
after_success: npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: dwoiq07LPXP/ng/Ob4dDM0OhreQ+0mmRUvvg5xpL59wBHnNmW0l2pWwsSO8nDYFneeH4z45JVQTZHqivlpaQljAXBo0d7FwOSLdE+AJDBA7hxfdWxiST0MwBwIyRbzOt0T1ttyISxAA/1jFK7HHLoVFhH/3ZILH2mG9Vn+UDMxApC1nz60ZOYbHzeh3CzWg4+8lnmK/A8aiwPEcpccJMJyBNRO4hiAsDnNUCOQrmmXcqWQHMNI/mf82DkPuyE8x/zrLrV93WIhpu6xrsUfbmo4ggjFm+6/v9vk1Ply0YnU5S7JXojCRcMxS2EmBMdZeTdffI04ayJqC6P4f2eu+ZC3ZVRNGf/sEv19985OxsulVmxAxwUdArBIGU5c6pzO9TvFchaOuGQfF8Y9iHOoy/NhUcc/cJb2w0Poy15bxwhANaQs++IMBonNn7l44wlG7eMB3N4ZBVhoDX3qvLy3XUcEmZE0S6hHbtbyJDd4YPd9qMPnMs8jUS0pWc7GOhViXZZia/aQEhYoxBH3ZKM+YelGvCW/JoFjQK2y0i3dCCWl8JmndZu5x7565etudMqaEqF7QFB/hoBWO3lzn2eCVvuoDY/jLfN/5VE4DN1yZd9Z+3GCxENolVGtrYoJCqimyi/TlygEk66ZtUbPk6CLDifLrJd8GpXp8nNQULCYgMrnk=
cache: yarn
